CREATE TABLE `buyers` (
	`id` int AUTO_INCREMENT NOT NULL,
	`fullName` varchar(255) NOT NULL,
	`phone` varchar(50) NOT NULL,
	`email` varchar(320) NOT NULL,
	`personalOrBusiness` enum('Personal','Business') NOT NULL DEFAULT 'Personal',
	`hasCoBuyer` int NOT NULL DEFAULT 0,
	`coBuyerName` varchar(255),
	`coBuyerEmail` varchar(320),
	`businessName` varchar(255),
	`representativeName` varchar(255),
	`streetAddress` varchar(500) NOT NULL,
	`city` varchar(100) NOT NULL,
	`state` varchar(2) NOT NULL DEFAULT 'FL',
	`zipCode` varchar(20) NOT NULL,
	`driverLicenseUrl` text,
	`preferredPayment` enum('Zelle','Cash App','Venmo','Credit or Debit Card','Wire Transfer','Other') NOT NULL DEFAULT 'Zelle',
	`status` enum('NEW','PSA_SENT','CFD_SENT','CONTRACTED','CANCELLED') NOT NULL DEFAULT 'NEW',
	`notes` text,
	`contractId` int,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `buyers_id` PRIMARY KEY(`id`)
);
